name: Build

on: [push, pull_request]

jobs:
  pre-build:
    runs-on: ubuntu-20.04

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      npm_cache_dir: ${{ steps.npm-cache.outputs.dir }}

    steps:
      - name: Check Duplicate Actions
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.3.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12"

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

  build:
    runs-on: ubuntu-20.04

    needs: pre-build
    if: ${{ needs.pre-build.outputs.should_skip != 'true' }}
    name: Build

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12"

      - uses: actions/cache@v2
        with:
          path: ${{ needs.pre-build.outputs.npm_cache_dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js dependencies
        run: npm install

      # - name: Linting Typescript code
      #   run: npm run lint:typescript

      - name: Linting ESLint config
        run: npm run lint:eslint-config

      - name: Linting code style format
        run: npm run lint:prettier

      - name: Bootstrapping packages
        run: npm run bootstrap

      - name: Linting @anyshop/core
        run: npx ng lint @anyshop/core

      - name: Building @anyshop/core
        run: npx ng build @anyshop/core --prod

      - name: Linting @anyshop/shared
        run: npx ng lint @anyshop/shared

      - name: Building @anyshop/shared
        run: npx ng build @anyshop/shared --prod
