name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Lint and build

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12"

      - name: Install Node.js dependencies
        run: npm install

      # - name: Linting Typescript code
      #   run: npm run lint:typescript

      - name: Linting ESLint config
        run: npm run lint:eslint-config

      - name: Linting code format
        run: npm run lint:prettier

      - name: Linting Angular build
        run: npx ng lint

      - name: Bootstrapping packages
        run: npm run bootstrap

      - name: Building @anyshop/core
        run: npx ng build @anyshop/core --prod

      - name: Building @anyshop/shared
        run: npx ng build @anyshop/shared --prod
